server:
  port: 8001

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  kafka:
    producer:
      bootstrap-servers: localhost:9092

client:
  intelligence-core-service:
    host: localhost


models:
  retrain-cron: 0/15 * * ? * *
