server:
  port: 80

spring:
  data:
    mongodb:
      database: piper
  main:
    web-application-type: reactive

client:
  intelligence-core-service:
    host: intelligence-core-service
    port: 8004
