version: "3.7"
services:
  frontend:
    build:
      context: ../service/frontend
      target: ${TARGET}
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    volumes:
      - ../service/frontend/:/frontend/
  home-service:
    build:
      context: ../service/home-service
      target: ${TARGET}
      dockerfile: Dockerfile
    ports:
      - "8001:80"
  routines-db:
    image: mongo:4.4.1
    ports:
      - "8002:27017"
    volumes:
      - routines-db:/data/db

volumes:
  routines-db:
