name: containers-ci

on: [push]

jobs:
  build-containers:
    runs-on: ubuntu-latest
    env:
       DOCKER_TARGET_PLATFORM: linux/arm64
    
    steps:
      - uses: actions/checkout@v2
      - name: Mock SSL certificates
        run: |
          touch service/home-service/piper.p12
          touch service/frontend/nginx/piper.pem
          touch service/frontend/nginx/piper.key
      - name: Build containers
        working-directory: ./deploy
        run: docker-compose build
